version: "3"

services:
  idle-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - 8080:8080
    container_name: idle-api
    restart: always
    depends_on:
      - idle-db
    networks:
      - idle-network

  idle-db:
    image: mysql
    container_name: idle-db
    ports:
      - 5507:3306
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: idle
      LANG: C.UTF-8
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - idle-network

networks:
  idle-network:
