version: "3"

services:
  docker-hello-app:
    build: .
    ports:
      - 8080:8080
    container_name: docker-hello-app
    restart: always
    depends_on:
      - docker-hello-mariadb
    networks:
      - hello-docker-network

  docker-hello-mariadb:
    image: mariadb
    container_name: docker-hello-mariadb
    ports:
      - 3307:3307
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - hello-docker-network

  docker-hello-redis:
    image: redis
    container_name: docker-hello-redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - hello-docker-network

networks:
  hello-docker-network:
