spring:
  config:
    activate:
      on-profile: oauth-local

oauth:
  kakao:
    grant: authorization_code
    client_id: client_id
    client_secret: client_secret
    redirect_uri: http://localhost:8080/oauth/redirect